### ISSUE TITLE
블록 #121766에서 싱크가 멈추는 문제

### ISSUE THREAD

**Issue by decentrandom** [decentrandom/decentrandom#6]
I[2019-08-29|07:18:58.661] Committed state                              module=state height=121876 txs=1 appHash=8857148375DC4C4B76C4F98C8FFA8A5830FEF29DE6CCBD1A5AF659CE1521C989
panic: Failed to process committed block (121877:14F91183DBBF900327D5F6B9A10F7E2F613DE58B64BE880717D2580D97FAB6CC): Wrong Block.Header.AppHash.  Expected 8857148375DC4C4B76C4F98C8FFA8A5830FEF29DE6CCBD1A5AF659CE1521C989, got D43868CB232E3117983ECDD12116355FE424BFE738E30F6E6E599F062962DBF4

goroutine 74 [running]:
github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc000a7a340)
	/home/ec2-user/go/pkg/mod/github.com/tendermint/tendermint@v0.32.1/blockchain/reactor.go:347 +0x1542
created by github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
	/home/ec2-user/go/pkg/mod/github.com/tendermint/tendermint@v0.32.1/blockchain/reactor.go:117 +0x

**Comment by decentrandom** [comment]
MsgNewRand의 구조 변경으로 인한 AppHash의 변화가 불가피해졌습니다. state 덤프를 통해 새로운 genesis.json으로 상태를 이전합니다.
